name: static_card_ads
description: Introducing StaticCardAds – a versatile Flutter library that empowers developers to create stunning and customizable static card ads effortlessly. Seamlessly integrate eye-catching card advertisements into your app with complete control over text content, colors, and more. Craft engaging promotional displays, offers, and announcements that captivate users, all while maintaining a polished and professional look. Elevate your app's user experience with StaticCardAds and effortlessly convey your message in style.
version: 1.0.0
homepage: https://linkedin.com/in/mihiramin13/
repository: https://github.com/DYNAMICMORTAL/static_card_ads

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null